/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:863d6bdd-5745-49e4-8a5a-e57cfc271aea",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wzS1KCwAI",
    "aws_user_pools_web_client_id": "5h1081s13agojrfat20fmi9do1",
    "oauth": {}
};


export default config;
